In [1]:
import numpy as np

# Load the data from the NPY file
file_path = r'E:\STUDY\Publications\Thesis\Brain Emotion Detection\Dataset\Practice with datasets\deap\DEAP_DE_X_y\DEAP_DE_X.npy'
data = np.load(file_path)

In [2]:
data.shape

(1280, 32, 42, 4)

# EMotion pos neg neutral as of SEED

In [2]:
import numpy as np

# Load the data from the NPY file
file_path = r'E:\STUDY\Publications\Thesis\Brain Emotion Detection\Dataset\Practice with datasets\deap\DEAP_DE_X_y\DEAP_DE_y.npy'
data = np.load(file_path)

# Create an empty list to store the classified emotions
classified_emotions = []

# Iterate through each row in the data
for row in data:
    valence, arousal, dominance, likings = row[0], row[1], row[2], row[3]

    # Adjusted decision logic for emotion classification with a threshold of 4.5
    if arousal > 6 and valence > 6 and dominance > 6:
        emotion_label = 'Positive'
    elif arousal > 6 and valence <= 4.5:
        emotion_label = 'Negative'
    elif valence > 6 and arousal <= 3 and dominance > 6:
        emotion_label = 'Positive'
    elif valence <= 4 and arousal <= 6.5 and dominance > 5:
        emotion_label = 'Negative'
    elif valence <= 5 and arousal <= 5 and dominance <= 6:
        emotion_label = 'Neutral'
    
    # Append the emotion label to the row
    row_with_label = np.append(row, emotion_label)
    classified_emotions.append(row_with_label)

# Convert the list to a NumPy array for further analysis if needed
classified_emotions = np.array(classified_emotions)

# Print the number of instances in each category
print(f"Positive Emotions: {np.sum(classified_emotions[:, -1] == 'Positive')}")
print(f"Negative Emotions: {np.sum(classified_emotions[:, -1] == 'Negative')}")
print(f"Neutral Emotions: {np.sum(classified_emotions[:, -1] == 'Neutral')}")

# Save the classified data to a new NPY file
#np.save('classified_emotions.npy', classified_emotions)


Positive Emotions: 466
Negative Emotions: 410
Neutral Emotions: 404


In [3]:
# Extract only the 4th column (emotion labels)
emotion_labels = classified_emotions[:, 4]

# Map the emotion labels to the desired values
emotion_mapping = {'Positive': 1, 'Neutral': 0, 'Negative': -1}
mapped_emotion_labels = np.vectorize(emotion_mapping.get)(emotion_labels)

# Print the mapped emotion labels
print(mapped_emotion_labels)

[ 1  1  1 ... -1 -1 -1]


In [4]:
np.save('deap_de_y_emotions.npy', mapped_emotion_labels)

In [82]:
import numpy as np

# Replace the file path with your actual file path
file_path = r'E:\STUDY\Publications\Thesis\Brain Emotion Detection\Dataset\Practice with datasets\Seed\de_LDS_Extracted\X and Y\y.npy'

# Load the NumPy array from the file
y = np.load(file_path)

# Count the unique classes and their frequencies
unique_classes, counts = np.unique(y, return_counts=True)

# Print the results
for class_label, count in zip(unique_classes, counts):
    print(f'Class {class_label}: {count} occurrences')


Class -1.0: 225 occurrences
Class 0.0: 225 occurrences
Class 1.0: 225 occurrences


# EMotion Valence

In [1]:
import numpy as np

# Load the data from the NPY file
file_path = r'E:\STUDY\Publications\Thesis\Brain Emotion Detection\Dataset\Practice with datasets\deap\PSD\DEAP_PSD_y.npy'
data = np.load(file_path)

In [2]:
data

array([[7.71, 7.6 , 6.9 , 7.83],
       [8.1 , 7.31, 7.28, 8.47],
       [8.58, 7.54, 9.  , 7.08],
       ...,
       [3.05, 7.01, 5.1 , 1.1 ],
       [3.99, 7.17, 4.85, 1.  ],
       [7.15, 4.03, 9.  , 1.88]])

In [8]:
# Select only the valence column
data_valence = data[:, 0]
data_valence

array([7.71, 8.1 , 8.58, ..., 3.05, 3.99, 7.15])

In [15]:
# Modify the values
data_valence_modified = np.where(data_valence < 5.1, 0, 1)

# Count the frequency of 0s and 1s
counts = np.bincount(data_valence_modified)

# Display the counts
print("Frequency of 0:", counts[0])
print("Frequency of 1:", counts[1])

Frequency of 0: 669
Frequency of 1: 611


In [16]:
# Specify the save path for the modified valence data
save_path_modified = r'E:\STUDY\Publications\Thesis\Brain Emotion Detection\Dataset\Practice with datasets\deap\DEAP_DE_X_y\DEAP_DE_valence_y.npy'

# Save the modified valence data in NPY format
np.save(save_path_modified, data_valence_modified)

# Emotion Arousal

In [17]:
data_arousal = data[:, 1]
data_arousal

array([7.6 , 7.31, 7.54, ..., 7.01, 7.17, 4.03])

In [18]:
# Modify the values
data_arousal_modified = np.where(data_arousal < 5.1, 0, 1)

# Count the frequency of 0s and 1s
counts = np.bincount(data_valence_modified)

# Display the counts
print("Frequency of 0:", counts[0])
print("Frequency of 1:", counts[1])

Frequency of 0: 669
Frequency of 1: 611


In [20]:
# Specify the save path for the modified valence data
save_path_modified = r'E:\STUDY\Publications\Thesis\Brain Emotion Detection\Dataset\Practice with datasets\deap\DEAP_DE_X_y\DEAP_DE_arousal_y.npy'

# Save the modified valence data in NPY format
np.save(save_path_modified, data_arousal_modified)

# Shuffle

In [3]:
from sklearn.utils import shuffle

In [33]:
X  = np.load(r'E:\STUDY\Publications\Thesis\Brain Emotion Detection\Dataset\Practice with datasets\deap\Time\DEAP_Time_Domain_X.npy')
y  = np.load(r'E:\STUDY\Publications\Thesis\Brain Emotion Detection\Dataset\Practice with datasets\deap\PSD\DEAP_PSD_valence_y.npy')
z  = np.load(r'E:\STUDY\Publications\Thesis\Brain Emotion Detection\Dataset\Practice with datasets\deap\PSD\DEAP_PSD_arousal_y.npy')
X_shuffled, y_shuffled, z_shuffled = shuffle(X, y, z)


data = X_shuffled
labels_edited = y_shuffled

labels_edited1 = y_shuffled
labels_edited2 = z_shuffled

#Splitting Dataset into train, validation, test 

final_labels1 = labels_edited1[1180:1280]
final_labels2 = labels_edited2[1180:1280]

# Get the unique labels and their counts for final_labels1
unique_labels1, label_counts1 = np.unique(final_labels1, return_counts=True)

# Print the unique labels and their counts for final_labels1
print("Final Labels 1:")
for label, count in zip(unique_labels1, label_counts1):
    print(f"Label: {label}, Count: {count}")

# Get the unique labels and their counts for final_labels2
unique_labels2, label_counts2 = np.unique(final_labels2, return_counts=True)

# Print the unique labels and their counts for final_labels2
print("\nFinal Labels 2:")
for label, count in zip(unique_labels2, label_counts2):
    print(f"Label: {label}, Count: {count}")


Final Labels 1:
Label: 0, Count: 52
Label: 1, Count: 48

Final Labels 2:
Label: 0, Count: 52
Label: 1, Count: 48


In [34]:
# Save X_shuffled
np.save('DEAP_Time_X.npy', X_shuffled)

# Save y_shuffled
np.save('DEAP_Time_valence_y.npy', y_shuffled)

# Save z_shuffled
np.save('DEAP_Time_arousal_y.npy', z_shuffled)

Final Labels 1:
Label: 0, Count: 48
Label: 1, Count: 52

Final Labels 2:
Label: 0, Count: 47
Label: 1, Count: 53
